image: node:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - e2e-test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - npm install
    - CI=false npm run build

e2e-test-job:   # This job runs in the test stage.
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: e2e-test
  script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm start &
    # run Cypress tests
    - npx cypress run --headless --browser chrome
  allow_failure: true

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  image: gitlab/dind
  services:
    - docker:dind
  variables:
        DOCKER_HOST: tcp://docker:2375
        DOCKER_TLS_CERTDIR: ""
        DOCKER_DRIVER: overlay2
  script:
    - "docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD"
    - "docker build -t pimvanhooren/vybes-frontend --no-cache ."
    - "docker push pimvanhooren/vybes-frontend"

