apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: vybes-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vybes-frontend
  template:
    metadata:
      labels:
        app: vybes-frontend
    spec:
      containers:
        - name: vybes-frontend
          image: pimvanhooren/vybes-frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: "REACT_APP_GATEWAY_URL"
              value: "http://api-gateway"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: vybes-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
  type: NodePort